name: Auto Publish Blog Posts by 손(Son/손민기)

# on:
#   schedule:
#     - cron: '*/1 * * * *'

on:
  push:
    branches:
      - master

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Required Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install gitpython
          pip install -r requirements.txt

      - name: Generate Blog Post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_blog_post.py

      - name: Commit Changes
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_NAME: ${{ secrets.MY_NAME }}
          MY_TOKEN : ${{ secrets.MY_TOKEN }}
        run: |
          git config --local user.email $MY_EMAIL
          git config --local user.name $MY_NAME

          git remote set-url origin https://$MY_NAME:$MY_TOKEN@github.com/smk692/smk692.github.io.git

          git add .
          git commit -m "Add a new blog post"
          git push

  deploy:
    needs: generate-blog-post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: v14.17.4

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Npm install
        run: npm install

      - name: Update blog
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_NAME: ${{ secrets.MY_NAME }}
          MY_TOKEN : ${{ secrets.MY_TOKEN }}
        run: |
          git config --local user.email $MY_EMAIL
          git config --local user.name $MY_NAME

          git remote set-url origin https://$MY_NAME:$MY_TOKEN@github.com/smk692/smk692.github.io.git

          npm run deploy