name: Auto Publish Blog Posts

on:
  schedule:
    - cron: '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Required Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Generate Blog Post
        run: python generate_blog_post.py

      - name: Commit Changes
        run: |
          git config --local user.email "smk692@naver.com"
          git config --local user.name "smk692"
          git add .
          git commit -m "Add a new blog post"
          git push
